@extends('layouts.main')

@section('title', 'Shipping Methods')

@section('content')

<div class="container">
    <div class="row justify-content-center align-items-center g-2">
        <div class="col">
            <h1 class="mt-5 mb-4 text-center">Shipping Methods</h1>
        </div>
    </div>
    <div class="row justify-content-center align-items-center g-2">
        <div class="col">
        <p>These are three popular shipping methods that you can use to deliver your packages:</p>
        <p>DHL: DHL is one of the world's leading logistics and shipping companies, offering fast and reliable shipping services to businesses and individuals worldwide. With DHL, you can ship your packages for as low as 2€. DHL provides a range of shipping options, including express and standard shipping, to ensure that your packages are delivered on time.</p>
        <p>Slovneská pošta: Slovneská pošta is the national postal service provider of Slovakia. It offers a wide range of shipping services, including domestic and international shipping, parcel delivery, and express shipping. With Slovneská pošta, you can ship your packages for as low as 2€. Slovneská pošta also provides tracking and insurance services to ensure that your packages are safe and secure during transit.</p>
        <p>GLS: GLS is a leading European logistics and shipping company, providing reliable and cost-effective shipping services across Europe and beyond. With GLS, you can ship your packages for as low as 2€. GLS offers a range of shipping options, including express and standard shipping, as well as additional services such as delivery confirmation and insurance. Whether you're shipping within Europe or internationally, GLS can help you get your packages delivered on time and in good condition.</p>
        <p>Generated by AI</p>
        </div>
    </div>
</div>

@endsection
